from django.db import models

key = "1b9cfb5bc09046c08d3b333f59f1f419"

# Create your models here.
class Standings(models.Model): 
        season = models.IntegerField()
        team_id = models.IntegerField()
        key = models.CharField(max_length=15)
        city = models.CharField(max_length= 55)
        fname = models.CharField(max_length=55)
        conference = models.CharField(max_length=25)
        division = models.CharField(max_length=25)
        wins = models.IntegerField()
        losses = models.IntegerField()
        home_wins = models.IntegerField()
        home_losses = models.IntegerField()
        away_wins = models.IntegerField()
        away_losses = models.IntegerField()
        streak = models.IntegerField()
        conference_rank = models.IntegerField()        

class ActivePlayer(models.Model):
        player_id = models.IntegerField()
        status = models.CharField(max_length=15)
        team_id = models.IntegerField()
        team = models.CharField(max_length=15)
        jersey = models.IntegerField()
        position = models.CharField(max_length=15)
        fname = models.CharField(max_length=55)
        lname = models.CharField(max_length=55)
        birthdate = models.DateTimeField()
        ethnicity = models.CharField(max_length=55)
        height = models.IntegerField()
        weight = models.IntegerField()

class ActiveTeams(models.Model):
        team_id = models.IntegerField()
        key = models.CharField(max_length=15)
        active = models.BooleanField()
        city = models.CharField(max_length=55)
        name = models.CharField(max_length=55)
        stadium_id = models.IntegerField()
        conference = models.CharField(max_length=25)
        logo = models.CharField(max_length=256)
        coach = models.CharField(max_length=55)

class BasicSchedule(models.Model):
        game_id = models.IntegerField()
        season = models.IntegerField()
        date_time = models.DateTimeField()
        away_team = models.CharField(max_length=15)
        home_team = models.CharField(max_length=15)
        away_team_id = models.IntegerField()
        home_team_id = models.IntegerField()
        stadium = models.IntegerField()
        away_team_score = models.IntegerField()
        home_team_score = models.IntegerField()

class TeamSeason(models.Model):
        stat_id = models.IntegerField()
        team_id = models.IntegerField()
        season = models.IntegerField()
        teamname = models.CharField(max_length=55)
        team = models.CharField(max_length=15)
        wins = models.IntegerField()
        losses = models.IntegerField()
        possessions = models.DecimalField(max_digits=10, decimal_places=2)
        totalgames = models.IntegerField()
        minutes = models.IntegerField()
        fieldgoals = models.DecimalField(max_digits=10, decimal_places=2)
        fieldpercent = models.DecimalField(max_digits=10, decimal_places=2)
        twogoals = models.DecimalField(max_digits=10, decimal_places=2)
        twopercent = models.DecimalField(max_digits=10, decimal_places=2)
        threegoals = models.DecimalField(max_digits=10, decimal_places=2)
        threepercent = models.DecimalField(max_digits=10, decimal_places=2)
        freegoals = models.DecimalField(max_digits=10, decimal_places=2)
        freepercent = models.DecimalField(max_digits=10, decimal_places=2)
        rebounds = models.DecimalField(max_digits=10, decimal_places=2)
        assists = models.DecimalField(max_digits=10, decimal_places=2)
        steals = models.DecimalField(max_digits=10, decimal_places=2)
        blocks = models.DecimalField(max_digits=10, decimal_places=2)
        turnovers = models.DecimalField(max_digits=10, decimal_places=2)
        points = models.DecimalField(max_digits=10, decimal_places=2)

class PlayerSeason(models.Model):
        stat_id = models.IntegerField()
        team_id = models.IntegerField()
        player_id = models.IntegerField()
        season = models.IntegerField()
        name = models.CharField(max_length=55)
        team = models.CharField(max_length=15)
        position = models.CharField(max_length=15)
        games = models.IntegerField()
        fieldgoals = models.DecimalField(max_digits=10, decimal_places=2)
        fieldpercent = models.DecimalField(max_digits=10, decimal_places=2)
        twogoals = models.DecimalField(max_digits=10, decimal_places=2)
        twopercent = models.DecimalField(max_digits=10, decimal_places=2)
        threegoals = models.DecimalField(max_digits=10, decimal_places=2)
        threepercent = models.DecimalField(max_digits=10, decimal_places=2)
        freegoals = models.DecimalField(max_digits=10, decimal_places=2)
        freepercent = models.DecimalField(max_digits=10, decimal_places=2)
        rebounds = models.DecimalField(max_digits=10, decimal_places=2)
        assists = models.DecimalField(max_digits=10, decimal_places=2)
        steals = models.DecimalField(max_digits=10, decimal_places=2)
        blocks = models.DecimalField(max_digits=10, decimal_places=2)
        turnovers = models.DecimalField(max_digits=10, decimal_places=2)
        points = models.DecimalField(max_digits=10, decimal_places=2)

class Headshot(models.Model):
        player_id = models.IntegerField()
        name = models.CharField(max_length=105)
        team_id = models.IntegerField()
        team = models.CharField(max_length=15)
        position = models.CharField(max_length=15)
        headshot = models.CharField(max_length=505)


